### ISSUE TITLE
Checking if has shortcode in blog

### ISSUE THREAD

**Issue by grappler** [flowplayer/wordpress-flowplayer#83]
### Requirement
I am working on "Flowplayer HTML5 for WordPress" where I would like the scripts to load on the top of the page only when the shortcode exists in the post. The data for the the shortcode is in a CPT. The shortcode contains the id of custom post type. e.g. `[flowplayer id="17"]`

### Code
This is code has been successful for check single posts but does not work on a blog page with multiple posts.
```php
$post = get_queried_object();
has_shortcode( $post->post_content, 'flowplayer' );
```

### Additional future requirements
When using caching the page is cached separately to the flowplayer CPT. I would like to invalidate the cache of the all the page with the shortcode when the cpt is updated.

### Possible solution
I thought I could solve both problems together by creating a hidden custom taxonomy. When the post is saved with the shortcode a term would be added with the shortcode id. I could then simply use is_tax() to check if the post includes the shortcode and then load the scripts.

### Alternate solution
I did think of using custom meta data but realized it was a bit more complicated to check if the post contained that custom meta data.

### Question
Is there something that could go wrong with hidden custom taxonomy method? Is there a better way of solving these two problems?

**Comment by TweetPressFr** [comment]
Hi, get queried object() retrieves the currently-queried object so on a tax page you won't be able to use ost->post_content.

`var_dump($post);`

**Comment by grappler** [comment]
@TweetPressFr Thanks, for that the reason I am trying to get feedback on this issue. On an archive page `get_queried_object();` returns `null`.

**Comment by TweetPressFr** [comment]
`is_tax()` will check for any archive page displayed, these are all part of the same process : checking the current queried page. So they return very different data according to the context. I think it will be better to check if your object is actually an instance of WP_Post with ` is_a( $post, 'WP_Post' )` before using it.

But anyway that does not help you. There is no easy way to achieve this. Even with your solutions because here you want post data which is super easy to retrieve on single view but not on archive pages unless you make your own query. Hope I'm clear and not telling you stupid things.

**Comment by grappler** [comment]
I solved it by using `global $wp_query;` I did a few other changes. You can see them in this commit https://github.com/flowplayer/wordpress-flowplayer/commit/cc4c6032919cc326f6fa4392ae6b03f4d4175a26

As using regex on every page load is not very performant I going to a custom taxonomy instead.

**Comment by TweetPressFr** [comment]
True for this but kinda complexe code to do these enhancements don't you think ? Anyway :+1:

**Comment by devinsays** [comment]
Hi @grappler. Forget all that, just enqueue the script when the output is rendered.

http://mikejolley.com/2013/12/sensible-script-enqueuing-shortcodes/

**Comment by grappler** [comment]
@devinsays Thanks for stopping by. That is the best method but the scripts are then loaded in the footer and I need the scripts to be loaded in the header.

**Comment by devinsays** [comment]
Hm, that makes it tricky. Have you found a solution?

I think it would be difficult to conditionally load from the head since you won't always know the queries that are going to happen. For instance, someone could make a custom page template with multiple loops. Or query for something in a widget area. I think you're probably stuck loading in on all pages.

**Comment by grappler** [comment]
Yes, I found a solution. I mentioned the solution in the above https://github.com/flowplayer/wordpress-flowplayer/issues/83#issuecomment-74391073
