### ISSUE TITLE
Add VAST ads support

### ISSUE THREAD

**Issue by grappler** [flowplayer/wordpress-flowplayer#95]
https://flowplayer.org/vast/
https://flowplayer.org/docs/vast.html
http://demos.flowplayer.org/ads/vast.html

``` php
        $vast_config = array(
            'ads' => array(
                array(
                    'time' => '',
                    'adTag' => '',
                )
            ),
        );
        $return['vast_config'] = apply_filters( 'fp5_avast_config', $vast_config, $return['id'] );
```

**Comment by mvarrieur** [comment]
I was just looking into this today, does the Wordpress plugin not yet support VAST? Trying to weigh my options here. I really like the plugin tho, it is super easy to use!

**Comment by mvarrieur** [comment]
Added a PR. Hopefully this at least gets us part of the way there!

**Comment by bbbo** [comment]
since we now have a completely rewritten VAST plugin, the docs at https://flowplayer.org/docs/vast.html are relevant.

This makes things a bit simpler (especially in contrast to the ASF plugin), as you only need to offer an ads: array with (optionally) several time: / adTag: combinations, or one adRules: field which points to an XML on the adserver.

We need configuration options for VpaidMode and redirects. Playlist options can probably wait.

**Comment by underdude** [comment]
Should configuration for VpaidMode and redirects be per video or global?
